### ISSUE TITLE
CentOS link error

### ISSUE THREAD

**Issue by hailinzeng** [Qv2ray/Qv2ray#366]
$ qmake
$ make -j 8

g++ ... -o qv2ray ...

v2ray_geosite.pb.o: In function `DomainObject_Attribute::InternalSerializeWithCachedSizesToArray(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const':
v2ray_geosite.pb.cc:(.text+0x6a4): undefined reference to `google::protobuf::io::EpsCopyOutputStream::WriteStringMaybeAliasedOutline(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
v2ray_geosite.pb.o: In function `DomainObject::InternalSerializeWithCachedSizesToArray(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const':
v2ray_geosite.pb.cc:(.text+0x9dc): undefined reference to `google::protobuf::io::EpsCopyOutputStream::WriteStringMaybeAliasedOutline(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
v2ray_geosite.pb.o: In function `GeoSite::InternalSerializeWithCachedSizesToArray(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const':
v2ray_geosite.pb.cc:(.text+0xc6c): undefined reference to `google::protobuf::io::EpsCopyOutputStream::WriteStringMaybeAliasedOutline(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
v2ray_geosite.pb.o: In function `DomainObject_Attribute::~DomainObject_Attribute()':
v2ray_geosite.pb.cc:(.text+0xf43): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
v2ray_geosite.pb.o: In function `DomainObject_Attribute::_InternalParse(char const*, google::protobuf::internal::ParseContext*)':
v2ray_geosite.pb.cc:(.text+0x11ad): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
v2ray_geosite.pb.cc:(.text+0x11c5): undefined reference to `google::protobuf::internal::InlineGreedyStringParserUTF8(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*, char const*)'
v2ray_geosite.pb.o: In function `DomainObject_Attribute::DomainObject_Attribute()':
v2ray_geosite.pb.cc:(.text+0x13d6): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
v2ray_geosite.pb.o: In function `DomainObject::_InternalParse(char const*, google::protobuf::internal::ParseContext*)':
v2ray_geosite.pb.cc:(.text+0x1781): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
v2ray_geosite.pb.cc:(.text+0x1799): undefined reference to `google::protobuf::internal::InlineGreedyStringParserUTF8(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*, char const*)'
v2ray_geosite.pb.o: In function `DomainObject::DomainObject()':
v2ray_geosite.pb.cc:(.text+0x192e): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
v2ray_geosite.pb.o: In function `GeoSite::_InternalParse(char const*, google::protobuf::internal::ParseContext*)':
v2ray_geosite.pb.cc:(.text+0x1cb1): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
v2ray_geosite.pb.cc:(.text+0x1cc9): undefined reference to `google::protobuf::internal::InlineGreedyStringParserUTF8(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*, char const*)'
v2ray_geosite.pb.o: In function `DomainObject::~DomainObject()':
v2ray_geosite.pb.cc:(.text+0x1e33): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
v2ray_geosite.pb.o: In function `GeoSite::GeoSite()':
v2ray_geosite.pb.cc:(.text+0x1f2e): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
v2ray_geosite.pb.o: In function `GeoSite::~GeoSite()':
v2ray_geosite.pb.cc:(.text+0x23d3): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
v2ray_geosite.pb.o: In function `DomainObject_Attribute::MergeFrom(DomainObject_Attribute const&)':
v2ray_geosite.pb.cc:(.text+0x2698): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
v2ray_geosite.pb.o: In function `DomainObject_Attribute::InternalSwap(DomainObject_Attribute*)':
v2ray_geosite.pb.cc:(.text+0x2920): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
v2ray_geosite.pb.o:v2ray_geosite.pb.cc:(.text+0x2bab): more undefined references to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]' follow
v2ray_geosite.pb.o:(.data.rel.ro._ZTV22DomainObject_Attribute[_ZTV22DomainObject_Attribute]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
v2ray_geosite.pb.o:(.data.rel.ro._ZTV22DomainObject_Attribute[_ZTV22DomainObject_Attribute]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
v2ray_geosite.pb.o:(.data.rel.ro._ZTV12DomainObject[_ZTV12DomainObject]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
v2ray_geosite.pb.o:(.data.rel.ro._ZTV12DomainObject[_ZTV12DomainObject]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
v2ray_geosite.pb.o:(.data.rel.ro._ZTV7GeoSite[_ZTV7GeoSite]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
v2ray_geosite.pb.o:(.data.rel.ro._ZTV7GeoSite[_ZTV7GeoSite]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
v2ray_geosite.pb.o:(.data.rel.ro._ZTV11GeoSiteList[_ZTV11GeoSiteList]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
v2ray_geosite.pb.o:(.data.rel.ro._ZTV11GeoSiteList[_ZTV11GeoSiteList]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
make: *** [qv2ray] Error 1

**System Information**

 - OS Type: CentOS 7.8
 - Built from the source, dev branch

**Other Info**

  - gcc 7
  - protobuf-3.10.1

**Comment by DuckSoft** [comment]
You may join https://t.me/qv2ray to discuss with us.

**Comment by hailinzeng** [comment]
issue solved. protobuf is build with gcc 4.8.5. 

After rebuild protobuf with gcc 7, error message is gone.

**Comment by DuckSoft** [comment]
Good.
